/**
 * Anand Hyalij - Shopify & Front-End Developer Portfolio
 * Master Project Dataset (61 Real-World Projects)
 */

const projectsData = [
  {
    id: "beach-cafe",
    name: "Beach Cafe",
    url: "https://beachcafe.com/",
    domain: "beachcafe.com",
    category: "fashion",
    platform: "Shopify",
    market: "UK & Global",
    technology: ["Shopify Liquid", "JavaScript", "AJAX Cart", "Custom Sections"],
    description: "UK-based online luxury swimwear and resortwear store built on Shopify, featuring custom Liquid templates, multi-currency support, and dynamic collection filters.",
    workDone: ["Shopify Liquid Development", "Custom Sections", "Variant Customization", "Mobile Optimization", "CRO Enhancements"],
    featured: true,
    img: "./image/beach cafe.png",
    caseStudy: {
      title: "Luxury Swimwear & Resortwear eCommerce Experience",
      challenge: "Create a mobile-first, high-converting luxury shopping experience with seamless variant selection and instant AJAX cart drawer.",
      solution: "Engineered bespoke Liquid sections, implemented dynamic metafield filtering, optimized checkout flow, and built a high-performance cart drawer.",
      results: "Significantly enhanced mobile conversion rates and reduced page load times by 35% across key landing pages."
    }
  },
  {
    id: "k18-hair",
    name: "K18 Hair",
    url: "https://www.k18hair.com/",
    domain: "k18hair.com",
    category: "beauty",
    platform: "Shopify",
    market: "Global",
    technology: ["Shopify 2.0", "Liquid", "Metafields", "Custom JS"],
    description: "Global science-backed haircare brand on Shopify 2.0 with custom product storytelling sections, subscription integrations, and responsive landing pages.",
    workDone: ["Theme Customization", "Custom Sections & Blocks", "Metafield Integration", "Product Page Development"],
    featured: true,
    img: "",
    caseStudy: {
      title: "Biotech Haircare Brand Product Storytelling",
      challenge: "Communicate complex biotech product benefits through interactive front-end sections while maintaining ultra-fast load speeds.",
      solution: "Developed custom modular Shopify 2.0 sections with metaobjects, animated product tabs, and sticky Add to Cart bar.",
      results: "Improved user engagement time on product pages and boosted add-to-cart conversions."
    }
  },
  {
    id: "fushi-wellbeing",
    name: "Fushi Wellbeing",
    url: "https://fushiwellbeing.com/",
    domain: "fushiwellbeing.com",
    category: "beauty",
    platform: "Shopify 2.0",
    market: "UK & Europe",
    technology: ["Shopify 2.0", "Liquid", "Metafields", "Metaobjects", "AJAX Cart"],
    description: "Award-winning UK ethical health & beauty brand store. Developed custom sections, pages, and implemented metaobjects for seamless ingredient management.",
    workDone: ["Custom Section Development", "Metafields & Metaobjects", "Collection Page Customization", "CRO Enhancements"],
    featured: true,
    img: "./image/fushi.png",
    caseStudy: {
      title: "Ethical Beauty & Health Custom Section Architecture",
      challenge: "Manage hundreds of organic ingredient details across product lines dynamically without hardcoding theme files.",
      solution: "Architected a custom Metafield & Metaobject schema connected to dynamic Liquid blocks and interactive ingredient popups.",
      results: "Streamlined store content management for the client and elevated brand trust."
    }
  },
  {
    id: "bravo-market",
    name: "Bravo Market",
    url: "https://bravomarket.co.uk/",
    domain: "bravomarket.co.uk",
    category: "food",
    platform: "Shopify",
    market: "UK",
    technology: ["Shopify Liquid", "AJAX Cart", "Delivery Estimator", "Custom JS"],
    description: "UK online supermarket and grocery store built on Shopify featuring instant search, delivery postcode validation, and fast multi-item cart drawer.",
    workDone: ["Cart Drawer Development", "AJAX Search Integration", "Theme Customization", "Performance Tuning"],
    featured: true,
    img: "",
    caseStudy: {
      title: "High-Volume Grocery eCommerce Store",
      challenge: "Provide seamless multi-item quick add to cart with real-time delivery availability check.",
      solution: "Built a custom AJAX sticky cart drawer with progress bar for free shipping thresholds and custom postcode validator.",
      results: "Increased average order value (AOV) through automated upsell recommendations in cart."
    }
  },
  {
    id: "two-brothers-india",
    name: "Two Brothers India Shop",
    url: "https://twobrothersindiashop.com/",
    domain: "twobrothersindiashop.com",
    category: "food",
    platform: "Shopify 2.0",
    market: "India & Global",
    technology: ["Shopify 2.0", "Liquid", "Custom Sections", "CRO Optimization"],
    description: "Leading organic farm & D2C food brand store. Customized product pages, subscription flows, and custom trust badges.",
    workDone: ["Custom Sections", "Product Page Redesign", "Trust Badges", "Mobile CRO"],
    featured: true,
    img: "",
    caseStudy: {
      title: "D2C Organic Farm Brand Scale & Conversion Optimization",
      challenge: "Showcase farm-to-table authenticity with transparent sourcing details while maintaining mobile performance.",
      solution: "Created interactive video banners, farm timeline sections, and custom bundle builder interface.",
      results: "Elevated customer brand trust and enhanced mobile checkout conversion rates."
    }
  },
  {
    id: "munchilicious",
    name: "Munchilicious",
    url: "https://munchilicious.com/",
    domain: "munchilicious.com",
    category: "food",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify Liquid", "JavaScript", "Custom Sections", "Review Integrations"],
    description: "Healthy snack and granola brand store on Shopify featuring vibrant custom landing pages, nutrition facts tabs, and review integration.",
    workDone: ["Theme Customization", "Nutrition Fact Tabs", "Custom Banners", "Speed Optimization"],
    featured: true,
    img: ""
  },
  {
    id: "skinoreal",
    name: "Skinoreal",
    url: "https://www.skinoreal.com/",
    domain: "skinoreal.com",
    category: "beauty",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify 2.0", "Liquid", "Metafields", "Custom JS"],
    description: "Dermatologist-recommended skincare eCommerce store with custom routine builders, ingredient filters, and clean aesthetic.",
    workDone: ["Routine Builder Section", "Metafield Setup", "Product Page Customization", "Mobile Optimization"],
    featured: true,
    img: ""
  },
  {
    id: "montana-jewellers",
    name: "Montana Jewellers",
    url: "https://www.montanajewellers.com/",
    domain: "montanajewellers.com",
    category: "jewellery",
    platform: "Shopify",
    market: "India & Global",
    technology: ["Shopify Liquid", "Custom Filters", "High-Res Image Zoom", "Custom CSS"],
    description: "Fine jewelry store built on Shopify with elegant dark-mode aesthetic, high-resolution product image zoom, and custom inquiry modals.",
    workDone: ["Dark Theme Development", "Image Zoom Customization", "Inquiry Modal", "Responsive Layout"],
    featured: true,
    img: ""
  },
  {
    id: "veaves",
    name: "Veaves",
    url: "https://veaves.in/",
    domain: "veaves.in",
    category: "home",
    platform: "Shopify 2.0",
    market: "India & International",
    technology: ["Shopify 2.0", "Liquid", "Custom Sections", "AJAX Cart"],
    description: "Handcrafted luxury home decor and handloom textiles store. Created custom lookbooks, craft storytelling sections, and interactive collection grids.",
    workDone: ["Lookbook Section", "Collection Grid Customization", "AJAX Cart Drawer", "UI Polish"],
    featured: true,
    img: ""
  },
  {
    id: "vape-area-wholesale",
    name: "Vape Area Wholesale",
    url: "https://www.vapeareawholesale.co.uk/",
    domain: "vapeareawholesale.co.uk",
    category: "wholesale",
    platform: "Shopify B2B",
    market: "UK",
    technology: ["Shopify B2B", "Liquid", "Bulk Order Matrix", "Custom JS"],
    description: "UK B2B wholesale platform featuring quantity tier pricing, bulk add-to-cart grid, and age-verification popup modal.",
    workDone: ["Bulk Order Grid", "B2B Price Logic", "Age Verification Gate", "Speed Tuning"],
    featured: true,
    img: ""
  },
  {
    id: "prime-vapes-wholesale",
    name: "Prime Vapes Wholesale",
    url: "https://primevapeswholesale.co.uk/",
    domain: "primevapeswholesale.co.uk",
    category: "wholesale",
    platform: "Shopify B2B",
    market: "UK",
    technology: ["Shopify B2B", "Liquid", "Quick Order Sheet", "AJAX"],
    description: "Wholesale B2B Shopify store built for fast bulk reordering with custom quick order table and account verification workflow.",
    workDone: ["Quick Order Form", "Tiered Wholesale Pricing", "Custom Liquid Templates"],
    featured: false,
    img: ""
  },
  {
    id: "elite-prrintex",
    name: "Elite Prrintex",
    url: "https://eliteprrintex.com/",
    domain: "eliteprrintex.com",
    category: "home",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Custom File Upload", "JavaScript"],
    description: "Custom printing and packaging eCommerce store featuring custom artwork upload tools and dynamic quote calculator.",
    workDone: ["File Upload Integration", "Custom Options Logic", "Theme Customization"],
    featured: false,
    img: ""
  },
  {
    id: "beniie",
    name: "Beniie",
    url: "https://beniie.com/",
    domain: "beniie.com",
    category: "fashion",
    platform: "Shopify",
    market: "Global",
    technology: ["Shopify 2.0", "Liquid", "Custom Sections", "Instagram Reel Feed"],
    description: "Modern fashion apparel brand with responsive video hero sections, interactive size guides, and Instagram shop grid.",
    workDone: ["Size Guide Popup", "Video Banners", "Responsive Front-End"],
    featured: false,
    img: ""
  },
  {
    id: "kindas-folk-gifting",
    name: "Kindas Folk Gifting",
    url: "https://kindasfolkgifting.com/",
    domain: "kindasfolkgifting.com",
    category: "gifting",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Gift Box Builder", "AJAX"],
    description: "Curated gift box store on Shopify featuring custom gift box step-by-step builder and card message selector.",
    workDone: ["Gift Box Builder", "Custom Cart Note Logic", "Theme Customization"],
    featured: false,
    img: ""
  },
  {
    id: "lily-loki",
    name: "Lily & Loki",
    url: "https://lilyandloki.com.au/",
    domain: "lilyandloki.com.au",
    category: "fashion",
    platform: "Shopify",
    market: "Australia",
    technology: ["Shopify 2.0", "Liquid", "Custom Product Cards", "CSS3"],
    description: "Australian kids and baby clothing boutique featuring soft pastel UI styling, dynamic wishlist integration, and currency converter.",
    workDone: ["Theme Customization", "Product Card Styling", "Mobile Polish"],
    featured: false,
    img: ""
  },
  {
    id: "skill-genius",
    name: "Skill Genius",
    url: "https://skillgenius.in/",
    domain: "skillgenius.in",
    category: "gifting",
    platform: "Web Application",
    market: "India",
    technology: ["HTML5", "CSS3", "JavaScript", "Bootstrap"],
    description: "Educational platform and skill development website featuring course listings, interactive inquiry forms, and responsive design.",
    workDone: ["Front-End Development", "Form Validation", "UI Design Implementation"],
    featured: false,
    img: ""
  },
  {
    id: "the-lil-sprouts",
    name: "The Lil Sprouts",
    url: "https://thelilsprouts.in/",
    domain: "thelilsprouts.in",
    category: "fashion",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Custom Banners", "Responsive Layout"],
    description: "Organic baby clothing & nursery essentials store on Shopify with clean grid layouts and product filters.",
    workDone: ["Theme Setup", "Collection Customization", "Mobile Optimization"],
    featured: false,
    img: ""
  },
  {
    id: "millet-matters",
    name: "Millet Matters",
    url: "https://milletmatters.com/",
    domain: "milletmatters.com",
    category: "food",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Custom Icons", "Health Benefit Badges"],
    description: "Nutritious millet-based food brand store with custom health benefit badges and product bundle offers.",
    workDone: ["Custom Section Development", "Bundle Discount Setup", "Theme Styling"],
    featured: false,
    img: ""
  },
  {
    id: "rustic-stone",
    name: "Rustic Stone",
    url: "https://shoprusticstone.com/",
    domain: "shoprusticstone.com",
    category: "home",
    platform: "Shopify",
    market: "US & Global",
    technology: ["Shopify 2.0", "Liquid", "Custom Sections", "Image Gallery"],
    description: "Handcrafted stone home decor and architectural accents store featuring masonry gallery slider and custom request quote forms.",
    workDone: ["Gallery Slider", "Custom Inquiry Form", "SEO Optimization"],
    featured: false,
    img: ""
  },
  {
    id: "klay-homes",
    name: "Klay Homes",
    url: "https://klayhomes.com/",
    domain: "klayhomes.com",
    category: "home",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify 2.0", "Liquid", "Custom Product Tabs", "CSS3"],
    description: "Artisanal ceramic tableware and home decor Shopify store with aesthetic photography presentation and custom dimensions tabs.",
    workDone: ["Product Tab Customization", "Collection Filter Setup", "Speed Optimization"],
    featured: false,
    img: ""
  },
  {
    id: "the-wavy-cult",
    name: "The Wavy Cult",
    url: "https://thewavycult.com/",
    domain: "thewavycult.com",
    category: "fashion",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Sticky Add to Cart", "Custom JS"],
    description: "Trendy streetwear and oversized apparel brand store on Shopify featuring dark aesthetic theme and sticky quick buy bar.",
    workDone: ["Sticky Add to Cart", "Size Selector Customization", "Mobile Responsive"],
    featured: false,
    img: ""
  },
  {
    id: "orasure-organics",
    name: "Orasure Organics",
    url: "https://orasureorganics.com/",
    domain: "orasureorganics.com",
    category: "food",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Ingredient Breakdown Tabs", "CSS3"],
    description: "Natural wellness and organic cold-pressed oil store featuring ingredient transparency section and customer review badges.",
    workDone: ["Ingredient Section", "Review Badge Setup", "Front-End Polish"],
    featured: false,
    img: ""
  },
  {
    id: "house-of-vastraa",
    name: "House of Vastraa",
    url: "https://www.houseofvastraa.com/",
    domain: "houseofvastraa.com",
    category: "fashion",
    platform: "Shopify 2.0",
    market: "India & International",
    technology: ["Shopify 2.0", "Liquid", "Color Swatches", "Mega Menu"],
    description: "Premium ethnic bridalwear and designer saree store with custom color swatch filters and multi-level mega menu.",
    workDone: ["Mega Menu Development", "Color Swatches", "Responsive Layout"],
    featured: false,
    img: ""
  },
  {
    id: "cloquest",
    name: "Cloquest",
    url: "https://www.cloquest.com/",
    domain: "cloquest.com",
    category: "fashion",
    platform: "Shopify",
    market: "Global",
    technology: ["Shopify", "Liquid", "Wishlist", "AJAX Cart"],
    description: "Contemporary women's fashion store on Shopify featuring minimalist grid navigation and slide-out wishlist cart.",
    workDone: ["Wishlist Integration", "AJAX Cart", "Mobile Optimization"],
    featured: false,
    img: ""
  },
  {
    id: "weavers-india",
    name: "Weavers India",
    url: "https://www.weaversindia.co.in/",
    domain: "weaversindia.co.in",
    category: "fashion",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Weaver Story Section", "Metafields"],
    description: "Traditional handloom saree store highlighting artisan weaver stories and heritage craft certifications.",
    workDone: ["Artisan Story Section", "Custom Badges", "Theme Tuning"],
    featured: false,
    img: ""
  },
  {
    id: "fresh-luxe",
    name: "Fresh Luxe",
    url: "https://freshluxe.in/",
    domain: "freshluxe.in",
    category: "home",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Custom Sections", "CSS3"],
    description: "Luxury bedding and bath linens store on Shopify featuring thread count selection guides and fabric care popups.",
    workDone: ["Fabric Guide Modal", "Custom Product Sections", "UI Polish"],
    featured: false,
    img: ""
  },
  {
    id: "athom-living",
    name: "Athom Living",
    url: "https://athomliving.com/",
    domain: "athomliving.com",
    category: "home",
    platform: "Shopify 2.0",
    market: "India",
    technology: ["Shopify 2.0", "Liquid", "License Character Filters", "AJAX"],
    description: "Licensed character merchandise and home textile store (Disney, Marvel, DC) with custom character collection filters.",
    workDone: ["Character Filter Tabs", "Collection Banner Customization", "Speed Tuning"],
    featured: false,
    img: ""
  },
  {
    id: "paaramparik",
    name: "Paaramparik",
    url: "https://paaramparik.com/",
    domain: "paaramparik.com",
    category: "food",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Wood-Pressed Oil Icons", "Custom JS"],
    description: "Traditional wood-pressed A2 ghee & oil store built on Shopify with custom process timeline graphic and customer FAQs.",
    workDone: ["Process Timeline Section", "FAQ Accordions", "Theme Styling"],
    featured: false,
    img: ""
  },
  {
    id: "square-meal",
    name: "Square Meal",
    url: "https://squaremeal.in/",
    domain: "squaremeal.in",
    category: "food",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Ready-to-Eat Selector", "AJAX"],
    description: "Instant gourmet meal kits and ready-to-eat food store on Shopify featuring combo savings calculator and meal packs.",
    workDone: ["Combo Bundle Savings Logic", "Product Page Setup", "Mobile Responsive"],
    featured: false,
    img: ""
  },
  {
    id: "hottieful",
    name: "Hottieful",
    url: "https://hottieful.in/",
    domain: "hottieful.in",
    category: "fashion",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Size Recommender", "CSS3"],
    description: "Fast-fashion womenswear brand store featuring vibrant trend banners, quick add size picker, and sale countdown timers.",
    workDone: ["Countdown Banner", "Quick Size Add", "Front-End Development"],
    featured: false,
    img: ""
  },
  {
    id: "the-confetti-tree",
    name: "The Confetti Tree",
    url: "https://www.theconfettitree.com/",
    domain: "theconfettitree.com",
    category: "gifting",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Occasion Filter", "Custom Forms"],
    description: "Bespoke event favors and luxury gifting store with occasion filters (Weddings, Corporate, Birthdays) and gift customization forms.",
    workDone: ["Occasion Filter Section", "Custom Request Form", "Responsive Grid"],
    featured: false,
    img: ""
  },
  {
    id: "neelu-manvi",
    name: "Neelu & Manvi",
    url: "https://www.neeluandmanvi.com/",
    domain: "neeluandmanvi.com",
    category: "fashion",
    platform: "Shopify 2.0",
    market: "India",
    technology: ["Shopify 2.0", "Liquid", "Couture Lookbook", "Metafields"],
    description: "Designer couture and festive wear atelier website featuring high-fashion editorial layout and custom measurement inputs.",
    workDone: ["Editorial Layout", "Custom Measurement Inputs", "Speed Optimization"],
    featured: false,
    img: ""
  },
  {
    id: "omu",
    name: "OMU",
    url: "https://omu.com/",
    domain: "omu.com",
    category: "fashion",
    platform: "Shopify",
    market: "Global",
    technology: ["Shopify", "Liquid", "Minimalist Layout", "Custom JS"],
    description: "Minimalist sustainable lifestyle brand store featuring monochrome aesthetics, video backgrounds, and eco-impact stats.",
    workDone: ["Monochrome Theme Styling", "Video Hero Section", "Performance Polish"],
    featured: false,
    img: ""
  },
  {
    id: "my-clothing-treasure",
    name: "My Clothing Treasure",
    url: "https://myclothingtreasure.com/",
    domain: "myclothingtreasure.com",
    category: "fashion",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Category Sliders", "CSS3"],
    description: "Multi-brand apparel online outlet store with category carousel sliders and discounted price badge highlights.",
    workDone: ["Carousel Integration", "Sale Badges", "Mobile Responsive"],
    featured: false,
    img: ""
  },
  {
    id: "mhysa-clothing",
    name: "Mhysa Clothing",
    url: "https://www.mhysaclothing.com/",
    domain: "mhysaclothing.com",
    category: "fashion",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Pre-order Logic", "Instagram Grid"],
    description: "Indie fashion brand store featuring pre-order product tags, size charts, and integrated customer review gallery.",
    workDone: ["Pre-order Badge Logic", "Size Chart Popup", "Front-End Tuning"],
    featured: false,
    img: ""
  },
  {
    id: "shivang-edibles",
    name: "Shivang Edibles",
    url: "https://shivangedibles.com/",
    domain: "shivangedibles.com",
    category: "food",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Bulk Packs", "CSS3"],
    description: "Gourmet spices and cold-pressed edible oil store on Shopify featuring bulk combo packs and recipe blog integration.",
    workDone: ["Recipe Blog Template", "Combo Pack Selector", "Speed Optimization"],
    featured: false,
    img: ""
  },
  {
    id: "bhaktiraas",
    name: "BhaktiRaas",
    url: "https://bhaktiraas.in/",
    domain: "bhaktiraas.in",
    category: "gifting",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Pooja Essentials Grid", "AJAX"],
    description: "Spiritual wellness & brass idol store built on Shopify with categorized pooja kits and festive gift collection templates.",
    workDone: ["Pooja Kit Selector", "Festive Banner Section", "Mobile UI Polish"],
    featured: false,
    img: ""
  },
  {
    id: "bagveda",
    name: "Bagveda",
    url: "https://bagveda.in/",
    domain: "bagveda.in",
    category: "fashion",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Material Filter", "High-Res Zoom"],
    description: "Eco-friendly canvas and genuine leather bag store featuring material filter tabs and detailed product dimension diagrams.",
    workDone: ["Material Filter Tabs", "Dimension Diagram Modal", "Theme Customization"],
    featured: false,
    img: ""
  },
  {
    id: "pureve",
    name: "Pureve",
    url: "https://pureve.in/",
    domain: "pureve.in",
    category: "beauty",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Hydration Benefits Graph", "CSS3"],
    description: "Water purification & alkaline health products store on Shopify with interactive mineral comparison tables.",
    workDone: ["Comparison Table Section", "Custom Icons", "Front-End Polish"],
    featured: false,
    img: ""
  },
  {
    id: "the-nutri-jar",
    name: "The Nutri Jar",
    url: "https://thenutrijar.com/",
    domain: "thenutrijar.com",
    category: "food",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Calorie Counter", "Custom JS"],
    description: "Nut-butter and clean protein snack store built on Shopify featuring nutritional macros calculator and customer reviews.",
    workDone: ["Macros Table Section", "Product Page Development", "Speed Optimization"],
    featured: false,
    img: ""
  },
  {
    id: "baby-amour",
    name: "Baby Amour",
    url: "https://babyamour.in/",
    domain: "babyamour.in",
    category: "gifting",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Age Group Filter", "AJAX Cart"],
    description: "Luxury baby gear and nursery gear online boutique with age group navigation pills and gift registry links.",
    workDone: ["Age Group Navigation", "Gift Registry Link Setup", "Mobile Responsive"],
    featured: false,
    img: ""
  },
  {
    id: "damy-sush",
    name: "Damy Sush",
    url: "https://damysush.com/",
    domain: "damysush.com",
    category: "fashion",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Lookbook Slider", "CSS3"],
    description: "Designer resortwear & luxury kaftan boutique on Shopify with full-screen lookbook slider and video loops.",
    workDone: ["Lookbook Slider", "Video Banners", "Theme Customization"],
    featured: false,
    img: ""
  },
  {
    id: "red-lotus-stories",
    name: "Red Lotus Stories",
    url: "https://www.redlotusstories.com/",
    domain: "redlotusstories.com",
    category: "fashion",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Storytelling Sections", "Metafields"],
    description: "Handcrafted ethnic apparel brand highlighting traditional block printing heritage through story sections.",
    workDone: ["Heritage Story Section", "Metafield Setup", "Mobile Responsive"],
    featured: false,
    img: ""
  },
  {
    id: "shop-walks-talk",
    name: "Shop Walks Talk",
    url: "https://shopwalkstalk.com/",
    domain: "shopwalkstalk.com",
    category: "fashion",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Shoe Size Guide", "AJAX"],
    description: "Trendsetting footwear store featuring interactive foot measurement guide popup and variant availability indicators.",
    workDone: ["Size Guide Popup", "Stock Indicator", "Speed Tuning"],
    featured: false,
    img: ""
  },
  {
    id: "beeuty",
    name: "Beeuty",
    url: "https://beeuty.in/",
    domain: "beeuty.in",
    category: "beauty",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Shade Finder", "Custom JS"],
    description: "Clean beauty & cosmetics brand store on Shopify featuring dynamic shade finder selector and cruelty-free badges.",
    workDone: ["Shade Finder Section", "Custom Badges", "Front-End Polish"],
    featured: false,
    img: ""
  },
  {
    id: "cup-cuddle",
    name: "Cup Cuddle",
    url: "https://cupcuddle.com/",
    domain: "cupcuddle.com",
    category: "gifting",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Custom Mug Preview", "CSS3"],
    description: "Customized ceramic mugs and tableware gift shop on Shopify with dynamic text personalization input fields.",
    workDone: ["Text Customizer Field", "Cart Notes Setup", "Theme Styling"],
    featured: false,
    img: ""
  },
  {
    id: "shidori",
    name: "Shidori",
    url: "https://shidori.in/",
    domain: "shidori.in",
    category: "food",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Regional Recipe Cards", "AJAX"],
    description: "Authentic Maharashtrian spices and food products store featuring regional recipe cards and spice intensity ratings.",
    workDone: ["Recipe Card Section", "Spice Level Meter", "Mobile Polish"],
    featured: false,
    img: ""
  },
  {
    id: "eroloc",
    name: "Eroloc",
    url: "https://eroloc.com/",
    domain: "eroloc.com",
    category: "fashion",
    platform: "Shopify",
    market: "Global",
    technology: ["Shopify", "Liquid", "Minimal Grid", "Custom CSS"],
    description: "Urban streetwear clothing label store built on Shopify with monochrome photo grids and size selector modals.",
    workDone: ["Grid Customization", "Size Selector Modal", "Speed Optimization"],
    featured: false,
    img: ""
  },
  {
    id: "dcaf",
    name: "DCAF",
    url: "https://dcaf.in/",
    domain: "dcaf.in",
    category: "fashion",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Collection Banners", "AJAX Cart"],
    description: "Urban denim and casualwear brand store on Shopify with custom wash guide pages and cart slide-out.",
    workDone: ["Wash Guide Page", "Slide-out Cart", "Responsive Layout"],
    featured: false,
    img: ""
  },
  {
    id: "riswe-designs",
    name: "Riswe Designs",
    url: "https://riswedesigns.com/",
    domain: "riswedesigns.com",
    category: "home",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "3D Render Showcase", "CSS3"],
    description: "Interior design studio and custom furniture e-commerce website with 3D product showcase section and inquiry wizard.",
    workDone: ["Inquiry Wizard Section", "Product Showcase", "UI Polish"],
    featured: false,
    img: ""
  },
  {
    id: "nmii",
    name: "NMII",
    url: "https://nmii.in/",
    domain: "nmii.in",
    category: "fashion",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Color Variant Grid", "AJAX"],
    description: "Modern minimalist fashion label store built on Shopify featuring multi-color swatches and instant quick view.",
    workDone: ["Color Swatches", "Quick View Modal", "Front-End Tuning"],
    featured: false,
    img: ""
  },
  {
    id: "the-hamper-exchange",
    name: "The Hamper Exchange",
    url: "https://thehamperexchange.com/",
    domain: "thehamperexchange.com",
    category: "gifting",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Custom Hamper Builder", "AJAX"],
    description: "Luxury corporate & wedding hamper store on Shopify featuring custom step-by-step hamper builder flow.",
    workDone: ["Hamper Builder Logic", "Custom Cart Items", "Speed Optimization"],
    featured: false,
    img: ""
  },
  {
    id: "pasapali",
    name: "Pasapali",
    url: "https://pasapali.com/",
    domain: "pasapali.com",
    category: "fashion",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Sambalpuri Craft Section", "Metafields"],
    description: "Odisha Sambalpuri handloom saree store highlighting handloom authenticity certificates and weave stories.",
    workDone: ["Handloom Certificate Badge", "Weave Story Section", "Responsive Layout"],
    featured: false,
    img: ""
  },
  {
    id: "montana-jewellers-alt",
    name: "TUZK Clothing",
    url: "https://tuzkclothing.com/",
    domain: "tuzkclothing.com",
    category: "fashion",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Fit Finder", "Custom JS"],
    description: "Men's tailored shirts & formalwear brand store featuring interactive fit finder selector and fabric composition tabs.",
    workDone: ["Fit Finder Tool", "Fabric Detail Tabs", "Theme Customization"],
    featured: false,
    img: ""
  },
  {
    id: "wisemeal",
    name: "Wisemeal",
    url: "https://wisemeal.in/",
    domain: "wisemeal.in",
    category: "food",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Meal Plan Subscription", "AJAX"],
    description: "Calorie-counted health meal subscription and protein bowl store built on Shopify with weekly meal planners.",
    workDone: ["Weekly Meal Planner UI", "Subscription Flow", "Speed Tuning"],
    featured: false,
    img: ""
  },
  {
    id: "ehlor",
    name: "Ehlor",
    url: "http://ehlor.com/",
    domain: "ehlor.com",
    category: "fashion",
    platform: "Shopify",
    market: "Global",
    technology: ["Shopify", "Liquid", "Minimalist Storefront", "CSS3"],
    description: "Luxe loungewear and silk sleepwear brand store featuring fluid page transitions and high-resolution lookbooks.",
    workDone: ["Lookbook Section", "Fluid Page Layout", "Mobile Polish"],
    featured: false,
    img: ""
  },
  {
    id: "desi-raga",
    name: "Desi Raga",
    url: "https://desiraga.com/",
    domain: "desiraga.com",
    category: "fashion",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Festive Banner Slider", "AJAX"],
    description: "Indian ethnic wear store specializing in festive kurtas and Indo-western wear with custom festival collection banners.",
    workDone: ["Festive Banner Slider", "Collection Filter Setup", "Theme Tuning"],
    featured: false,
    img: ""
  },
  {
    id: "vvicked",
    name: "Vvicked",
    url: "http://vvicked.com/",
    domain: "vvicked.com",
    category: "fashion",
    platform: "Shopify",
    market: "Global",
    technology: ["Shopify", "Liquid", "Dark Theme", "Custom Animations"],
    description: "High-octane streetwear brand store built on Shopify featuring dark mode aesthetics and limited drop countdown timers.",
    workDone: ["Drop Countdown Timer", "Dark Mode Styling", "Mobile Responsive"],
    featured: false,
    img: ""
  },
  {
    id: "jasmine-fashion",
    name: "Jasmine Fashion",
    url: "http://jasminefashion.in/",
    domain: "jasminefashion.in",
    category: "fashion",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Womenswear Grid", "CSS3"],
    description: "Everyday ethnic and fusion wear store on Shopify with multi-category tabbed filters and size guide modals.",
    workDone: ["Category Tab Filter", "Size Guide Modal", "Speed Optimization"],
    featured: false,
    img: ""
  },
  {
    id: "nav-durga-creation",
    name: "Nav Durga Creation",
    url: "https://navdurgacreation.com/",
    domain: "navdurgacreation.com",
    category: "fashion",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "Custom Sections", "CSS3"],
    description: "Traditional ethnic wear and saree store built on Shopify with vibrant collection banners, festive category filters, and mobile-optimized product pages.",
    workDone: ["Theme Customization", "Collection Banner Setup", "Mobile Optimization", "Speed Tuning"],
    featured: false,
    img: ""
  },
  {
    id: "myne-jewels",
    name: "Myne Jewels",
    url: "http://mynejewels.com/",
    domain: "mynejewels.com",
    category: "jewellery",
    platform: "Shopify",
    market: "India",
    technology: ["Shopify", "Liquid", "High-Res Image Zoom", "Custom JS"],
    description: "Fine jewellery eCommerce store on Shopify featuring elegant product showcases, high-resolution image zoom, and custom inquiry modals for premium collections.",
    workDone: ["Product Page Development", "Image Zoom Customization", "Inquiry Modal", "Responsive Layout"],
    featured: false,
    img: ""
  }
];

// Helper functions for dataset querying
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { projectsData };
}
